### ISSUE TITLE
Windows line breaks make dev-web-server execution fail on macOS

### ISSUE THREAD

**Issue by yamass** [manufitoussi/dev-web-server#4]
> dev-web-server
env: node\r: No such file or directory

Solution:

> dos2unix /Users/yamass/.config/yarn/global/node_modules/dev-web-server/web-server/app.js

**Comment by manufitoussi** [comment]
Thanks, I am preparing a version that fixes this issue.

**Comment by manufitoussi** [comment]
Fixed in [v1.6.2](https://github.com/manufitoussi/dev-web-server/tree/v1.6.2)
